/**
 * Strongly-typed aliases derived from the auto-generated `Database` schema.
 *
 * Why this file exists:
 *  - `src/integrations/supabase/types.ts` is regenerated by Lovable / the
 *    Supabase CLI on every migration. Never edit it by hand.
 *  - When a column or table is missing from the DB, the generated types will
 *    not include it — so any helper that depends on these aliases will fail
 *    to compile. That is the desired safety net: it forces us to add a
 *    migration before changing call sites.
 *
 * To regenerate after a schema change:
 *   PROJECT_REF=<ref> ./scripts/regen-supabase-types.sh
 *   (or just let Lovable auto-sync after running a migration)
 */
import type { Database } from "./types";

export type Tables = Database["public"]["Tables"];
export type TableName = keyof Tables;

export type Row<T extends TableName> = Tables[T]["Row"];
export type Insert<T extends TableName> = Tables[T]["Insert"];
export type Update<T extends TableName> = Tables[T]["Update"];

// Equipment domain row aliases — single source of truth.
export type EquipmentItemRow = Row<"equipment_items">;
export type EquipmentItemInsert = Insert<"equipment_items">;
export type EquipmentItemUpdate = Update<"equipment_items">;

export type EquipmentVariantRow = Row<"equipment_variants">;
export type EquipmentDistributionRow = Row<"equipment_distributions">;

export type EquipmentCategoryRow = Row<"equipment_categories">;
export type EquipmentCategoryInsert = Insert<"equipment_categories">;

export type EquipmentStockHistoryRow = Row<"equipment_stock_history">;
export type EquipmentStockHistoryInsert = Insert<"equipment_stock_history">;

export type EquipmentStockOpnameRow = Row<"equipment_stock_opname">;
export type EquipmentStockOpnameInsert = Insert<"equipment_stock_opname">;

export type EquipmentSettingsRow = Row<"equipment_settings">;
export type EquipmentNotificationSettingsRow = Row<"equipment_notification_settings">;