-- Seed permissions_list and menu_items for admin panel
-- Idempotent: safe to run multiple times

-- =========================
-- Seed permissions_list
-- =========================
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES
  ('dashboard', 'Dashboard', 'Overview', 'Akses ke dashboard utama admin'),
  ('analytics', 'Analytics', 'Overview', 'Akses ke halaman analytics'),
  ('packages', 'Paket', 'Produk & Operasional', 'Manajemen paket umroh/haji'),
  ('departures', 'Keberangkatan', 'Produk & Operasional', 'Manajemen jadwal keberangkatan'),
  ('bookings', 'Booking', 'Produk & Operasional', 'Manajemen pesanan jamaah'),
  ('equipment', 'Perlengkapan', 'Produk & Operasional', 'Manajemen perlengkapan jamaah'),
  ('itinerary-templates', 'Template Itinerary', 'Produk & Operasional', 'Template itinerary perjalanan'),
  ('savings', 'Tabungan', 'Produk & Operasional', 'Tabungan umroh jamaah'),
  ('room-assignments', 'Kamar', 'Produk & Operasional', 'Penugasan kamar hotel'),
  ('customers', 'Jamaah', 'Jamaah & Agent', 'Manajemen data jamaah'),
  ('agents', 'Agent', 'Jamaah & Agent', 'Manajemen agen'),
  ('branches', 'Cabang', 'Jamaah & Agent', 'Manajemen cabang'),
  ('loyalty', 'Loyalty', 'Jamaah & Agent', 'Program loyalty jamaah'),
  ('referrals', 'Referral', 'Jamaah & Agent', 'Sistem referral'),
  ('haji', 'Haji', 'Jamaah & Agent', 'Manajemen haji'),
  ('manasik', 'Manasik', 'Jamaah & Agent', 'Jadwal & materi manasik'),
  ('visa', 'Visa', 'Jamaah & Agent', 'Manajemen visa'),
  ('payments', 'Pembayaran', 'Keuangan & Akuntansi', 'Manajemen pembayaran'),
  ('finance-cash', 'Kas & Bank', 'Keuangan & Akuntansi', 'Kas dan rekening bank'),
  ('finance-ar', 'Piutang Jamaah', 'Keuangan & Akuntansi', 'Account Receivable'),
  ('finance-ap', 'Hutang Vendor', 'Keuangan & Akuntansi', 'Account Payable'),
  ('finance-pl', 'Laporan Laba Rugi', 'Keuangan & Akuntansi', 'Profit & Loss Statement'),
  ('leads', 'CRM Leads', 'Sales & CRM', 'Manajemen leads CRM'),
  ('coupons', 'Kupon', 'Sales & CRM', 'Manajemen kupon diskon'),
  ('landing-pages', 'Landing Page', 'Sales & CRM', 'Builder landing page'),
  ('hr', 'Data Karyawan', 'SDM (HR)', 'Manajemen data karyawan'),
  ('payroll', 'Penggajian / Payroll', 'SDM (HR)', 'Penggajian karyawan'),
  ('document-verification', 'Verifikasi Dokumen', 'Dokumen & Surat', 'Verifikasi dokumen jamaah'),
  ('documents-generator', 'Generate Surat', 'Dokumen & Surat', 'Generator surat & dokumen'),
  ('offline-content', 'Konten Offline', 'Dokumen & Surat', 'Konten offline jamaah PWA'),
  ('airlines', 'Maskapai', 'Master Data', 'Master data maskapai'),
  ('airports', 'Bandara', 'Master Data', 'Master data bandara'),
  ('hotels', 'Hotel', 'Master Data', 'Master data hotel'),
  ('muthawifs', 'Muthawif', 'Master Data', 'Master data muthawif'),
  ('bus-providers', 'Bus Provider', 'Master Data', 'Master data penyedia bus'),
  ('vendors', 'Vendor', 'Master Data', 'Master data vendor'),
  ('master-data', 'Master Data Hub', 'Master Data', 'Hub master data'),
  ('support', 'Tiket Support', 'Support & Komunikasi', 'Tiket support customer'),
  ('whatsapp', 'WhatsApp', 'Support & Komunikasi', 'Komunikasi WhatsApp'),
  ('marketing-materials', 'Materi Promosi', 'Support & Komunikasi', 'Materi promosi marketing'),
  ('reports', 'Laporan', 'Laporan', 'Laporan operasional'),
  ('advanced-reports', 'Laporan Lanjutan', 'Laporan', 'Laporan analitik lanjutan'),
  ('scheduled-reports', 'Laporan Terjadwal', 'Laporan', 'Laporan terjadwal otomatis'),
  ('users', 'Manajemen User', 'Pengaturan', 'Manajemen pengguna sistem'),
  ('security-audit', 'Security Audit', 'Pengaturan', 'Audit keamanan sistem'),
  ('2fa-settings', '2FA Settings', 'Pengaturan', 'Pengaturan autentikasi 2 faktor'),
  ('appearance', 'Tampilan', 'Pengaturan', 'Pengaturan tampilan website'),
  ('static-pages', 'Halaman Statis', 'Pengaturan', 'Halaman statis website'),
  ('testimonials', 'Testimoni', 'Pengaturan', 'Manajemen testimoni'),
  ('package-types', 'Tipe Paket', 'Pengaturan', 'Master tipe paket'),
  ('settings', 'Pengaturan', 'Pengaturan', 'Pengaturan sistem')
ON CONFLICT (key) DO UPDATE SET
  label = EXCLUDED.label,
  group_name = EXCLUDED.group_name,
  description = EXCLUDED.description;

-- =========================
-- Seed menu_items
-- =========================
INSERT INTO public.menu_items (key, label, path, icon, group_name, sort_order, required_permission) VALUES
  ('dashboard', 'Dashboard', '/admin', 'LayoutDashboard', 'Overview', 1, 'dashboard'),
  ('analytics', 'Analytics', '/admin/analytics', 'BarChart3', 'Overview', 2, 'analytics'),
  ('packages', 'Paket', '/admin/packages', 'Package', 'Produk & Operasional', 1, 'packages'),
  ('departures', 'Keberangkatan', '/admin/departures', 'CalendarDays', 'Produk & Operasional', 2, 'departures'),
  ('bookings', 'Booking', '/admin/bookings', 'BookOpen', 'Produk & Operasional', 3, 'bookings'),
  ('equipment', 'Perlengkapan', '/admin/equipment', 'Backpack', 'Produk & Operasional', 4, 'equipment'),
  ('itinerary-templates', 'Template Itinerary', '/admin/itinerary-templates', 'Map', 'Produk & Operasional', 5, 'itinerary-templates'),
  ('savings', 'Tabungan', '/admin/savings', 'Wallet', 'Produk & Operasional', 6, 'savings'),
  ('room-assignments', 'Kamar', '/admin/room-assignments', 'BedDouble', 'Produk & Operasional', 7, 'room-assignments'),
  ('customers', 'Jamaah', '/admin/customers', 'Users', 'Jamaah & Agent', 1, 'customers'),
  ('agents', 'Agent', '/admin/agents', 'UserSquare2', 'Jamaah & Agent', 2, 'agents'),
  ('branches', 'Cabang', '/admin/branches', 'Network', 'Jamaah & Agent', 3, 'branches'),
  ('loyalty', 'Loyalty', '/admin/loyalty', 'Gift', 'Jamaah & Agent', 4, 'loyalty'),
  ('referrals', 'Referral', '/admin/referrals', 'Share2', 'Jamaah & Agent', 5, 'referrals'),
  ('haji', 'Haji', '/admin/haji', 'Star', 'Jamaah & Agent', 6, 'haji'),
  ('manasik', 'Manasik', '/admin/manasik', 'GraduationCap', 'Jamaah & Agent', 7, 'manasik'),
  ('visa', 'Visa', '/admin/visa', 'StickyNote', 'Jamaah & Agent', 8, 'visa'),
  ('payments', 'Pembayaran', '/admin/payments', 'CreditCard', 'Keuangan & Akuntansi', 1, 'payments'),
  ('finance-cash', 'Kas & Bank', '/admin/finance-cash', 'Coins', 'Keuangan & Akuntansi', 2, 'finance-cash'),
  ('finance-ar', 'Piutang Jamaah', '/admin/finance/ar', 'TrendingUp', 'Keuangan & Akuntansi', 3, 'finance-ar'),
  ('finance-ap', 'Hutang Vendor', '/admin/finance/ap', 'TrendingDown', 'Keuangan & Akuntansi', 4, 'finance-ap'),
  ('finance-pl', 'Laporan Laba Rugi', '/admin/finance', 'PieChart', 'Keuangan & Akuntansi', 5, 'finance-pl'),
  ('leads', 'CRM Leads', '/admin/leads', 'UserPlus', 'Sales & CRM', 1, 'leads'),
  ('coupons', 'Kupon', '/admin/coupons', 'Ticket', 'Sales & CRM', 2, 'coupons'),
  ('landing-pages', 'Landing Page', '/admin/landing-pages', 'Globe', 'Sales & CRM', 3, 'landing-pages'),
  ('hr', 'Data Karyawan', '/admin/hr', 'Contact2', 'SDM (HR)', 1, 'hr'),
  ('payroll', 'Penggajian / Payroll', '/admin/hr/payroll', 'Banknote', 'SDM (HR)', 2, 'payroll'),
  ('document-verification', 'Verifikasi Dokumen', '/admin/document-verification', 'FileCheck', 'Dokumen & Surat', 1, 'document-verification'),
  ('documents-generator', 'Generate Surat', '/admin/documents-generator', 'FileText', 'Dokumen & Surat', 2, 'documents-generator'),
  ('offline-content', 'Konten Offline', '/admin/offline-content', 'BookOpen', 'Dokumen & Surat', 3, 'offline-content'),
  ('airlines', 'Maskapai', '/admin/airlines', 'Plane', 'Master Data', 1, 'airlines'),
  ('airports', 'Bandara', '/admin/airports', 'Building', 'Master Data', 2, 'airports'),
  ('hotels', 'Hotel', '/admin/hotels', 'Hotel', 'Master Data', 3, 'hotels'),
  ('muthawifs', 'Muthawif', '/admin/muthawifs', 'UserCheck', 'Master Data', 4, 'muthawifs'),
  ('bus-providers', 'Bus Provider', '/admin/bus-providers', 'Bus', 'Master Data', 5, 'bus-providers'),
  ('vendors', 'Vendor', '/admin/vendors', 'Store', 'Master Data', 6, 'vendors'),
  ('support', 'Tiket Support', '/admin/support', 'LifeBuoy', 'Support & Komunikasi', 1, 'support'),
  ('whatsapp', 'WhatsApp', '/admin/whatsapp', 'MessageSquare', 'Support & Komunikasi', 2, 'whatsapp'),
  ('marketing-materials', 'Materi Promosi', '/admin/marketing-materials', 'Megaphone', 'Support & Komunikasi', 3, 'marketing-materials'),
  ('reports', 'Laporan', '/admin/reports', 'FileBarChart', 'Laporan', 1, 'reports'),
  ('advanced-reports', 'Laporan Lanjutan', '/admin/advanced-reports', 'BarChart2', 'Laporan', 2, 'advanced-reports'),
  ('scheduled-reports', 'Laporan Terjadwal', '/admin/scheduled-reports', 'CalendarClock', 'Laporan', 3, 'scheduled-reports'),
  ('users', 'Manajemen User', '/admin/users', 'UserCog', 'Pengaturan', 1, 'users'),
  ('security-audit', 'Security Audit', '/admin/security-audit', 'ShieldAlert', 'Pengaturan', 2, 'security-audit'),
  ('2fa-settings', '2FA Settings', '/admin/2fa', 'KeyRound', 'Pengaturan', 3, '2fa-settings'),
  ('appearance', 'Tampilan', '/admin/appearance', 'Palette', 'Pengaturan', 4, 'appearance'),
  ('package-types', 'Tipe Paket', '/admin/package-types', 'Layers', 'Pengaturan', 5, 'package-types'),
  ('settings', 'Pengaturan', '/admin/settings', 'Settings', 'Pengaturan', 6, 'settings')
ON CONFLICT (key) DO UPDATE SET
  label = EXCLUDED.label,
  path = EXCLUDED.path,
  icon = EXCLUDED.icon,
  group_name = EXCLUDED.group_name,
  sort_order = EXCLUDED.sort_order,
  required_permission = EXCLUDED.required_permission,
  updated_at = now();