import { Router, type IRouter } from "express";
import healthRouter from "./health";
import v1Router from "./v1/index.js";
import emailRouter from "./email.js";
import midtransRouter from "./midtrans.js";
import pushRouter from "./push.js";
import manifestRouter from "./manifest.js";
import whatsappRouter from "./whatsapp.js";
import agentsRouter from "./agents.js";
import hrRouter from "./hr.js";
import remindersRouter from "./reminders.js";
import totpRouter from "./totp.js";
import permissionsRouter from "./permissions.js";
import bookingsRouter from "./bookings.js";
import authRouter from "./auth.js";
import functionsRouter from "./functions.js";
import dashboardRouter from "./dashboard.js";
import schedulerRouter from "./scheduler.js";
import reportsRouter from "./reports.js";
import migrationsRouter from "./migrations.js";
import cancellationRulesRouter from "./cancellationRules.js";
import publicPaymentsRouter from "./publicPayments.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(manifestRouter);
router.use("/auth", authRouter);
router.use("/functions", functionsRouter);
router.use("/v1", v1Router);
router.use("/email", emailRouter);
router.use("/midtrans", midtransRouter);
router.use("/push", pushRouter);
router.use("/whatsapp", whatsappRouter);
router.use("/agents", agentsRouter);
router.use("/hr", hrRouter);
router.use("/reminders", remindersRouter);
router.use("/totp", totpRouter);
router.use("/permissions", permissionsRouter);
router.use("/bookings", bookingsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/scheduler", schedulerRouter);
router.use("/reports", reportsRouter);
router.use("/admin/migrations", migrationsRouter);
router.use("/cancellation-rules", cancellationRulesRouter);
router.use("/public/payments", publicPaymentsRouter);

export default router;
