-- Tambahkan atau perbarui kunci permission agar sesuai dengan AdminLayout.tsx
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES 
('dashboard.view', 'Lihat Dashboard', 'Sistem & Pengaturan', 'Akses dashboard utama'),
('analytics.view', 'Lihat Analytics', 'Sistem & Pengaturan', 'Melihat analitik'),
('leads.view', 'Lihat Leads', 'Leads & Marketing', 'Melihat daftar leads'),
('marketing.view', 'Lihat Marketing', 'Leads & Marketing', 'Melihat data kupon, promosi, loyalty, dan referral'),
('settings.manage', 'Kelola Pengaturan', 'Sistem & Pengaturan', 'Akses penuh ke pengaturan sistem, landing page, dan tampilan'),
('packages.view', 'Lihat Paket', 'Paket & Keberangkatan', 'Melihat daftar paket dan tabungan'),
('departures.view', 'Lihat Keberangkatan', 'Paket & Keberangkatan', 'Melihat daftar keberangkatan'),
('bookings.view_own', 'Lihat Booking Sendiri', 'Booking & Jamaah', 'Melihat booking milik pengguna sendiri'),
('equipment.view', 'Lihat Perlengkapan', 'Operasional', 'Melihat data perlengkapan'),
('itinerary.view', 'Lihat Itinerary', 'Operasional', 'Melihat template itinerary'),
('operational.rooms.view', 'Lihat Kamar', 'Operasional', 'Manajemen penempatan kamar'),
('payments.view_own', 'Lihat Pembayaran Sendiri', 'Keuangan & Pembayaran', 'Melihat pembayaran milik pengguna'),
('payments.view_all', 'Lihat Semua Pembayaran', 'Keuangan & Pembayaran', 'Melihat semua riwayat pembayaran dan piutang/hutang'),
('finance.reports', 'Laporan Keuangan', 'Keuangan & Pembayaran', 'Melihat laporan laba rugi'),
('customers.view', 'Lihat Jamaah', 'Data Jamaah', 'Melihat profil jamaah'),
('agents.view', 'Lihat Agen', 'Sistem & Pengaturan', 'Melihat daftar agen'),
('settings.view', 'Lihat Pengaturan', 'Sistem & Pengaturan', 'Melihat pengaturan sistem dan cabang'),
('operational.view', 'Lihat Operasional', 'Operasional', 'Akses data operasional haji'),
('operational.manasik.view', 'Lihat Manasik', 'Operasional', 'Melihat jadwal manasik'),
('departures.visa.view', 'Lihat Visa', 'Operasional', 'Melihat status pengurusan visa'),
('hr.employees.view', 'Lihat Karyawan', 'SDM (HR)', 'Melihat data karyawan'),
('hr.attendance.view', 'Lihat Absensi', 'SDM (HR)', 'Melihat data absensi'),
('hr.payroll.view', 'Lihat Payroll', 'SDM (HR)', 'Melihat data penggajian dan slip gaji'),
('hr.departments.view', 'Lihat Departemen', 'SDM (HR)', 'Melihat data departemen'),
('hr.positions.view', 'Lihat Posisi', 'SDM (HR)', 'Melihat data posisi'),
('hr.schedules.view', 'Lihat Jadwal Kerja', 'SDM (HR)', 'Melihat jadwal kerja'),
('hr.devices.view', 'Lihat Perangkat', 'SDM (HR)', 'Melihat perangkat HR'),
('hr.settings.view', 'Lihat Pengaturan HR', 'SDM (HR)', 'Mengakses pengaturan HR'),
('support.tickets.view', 'Lihat Tiket Support', 'Support', 'Melihat tiket bantuan pelanggan'),
('whatsapp.view', 'Lihat WhatsApp', 'Support', 'Akses integrasi WhatsApp'),
('marketing_materials.view', 'Materi Promosi', 'Support', 'Akses folder materi promosi'),
('master_data.view', 'Lihat Master Data', 'Sistem & Pengaturan', 'Melihat master data'),
('bookings.document.view', 'Verifikasi Dokumen', 'Booking & Jamaah', 'Verifikasi dokumen jamaah'),
('documents.generator.view', 'Generate Surat', 'Sistem & Pengaturan', 'Membuat surat otomatis'),
('offline_content.view', 'Konten Offline', 'Sistem & Pengaturan', 'Akses konten offline'),
('reports.view', 'Lihat Laporan', 'Sistem & Pengaturan', 'Melihat laporan sistem'),
('users.view', 'Lihat Pengguna', 'Sistem & Pengaturan', 'Melihat daftar pengguna'),
('documents.verification.view', 'Verifikasi Dokumen', 'Booking & Jamaah', 'Verifikasi dokumen jamaah')
ON CONFLICT (key) DO UPDATE SET 
  label = EXCLUDED.label, 
  group_name = EXCLUDED.group_name;
