-- Sync permissions from frontend to database with correct labels and groups

-- Bookings
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('bookings.view_all', 'Lihat Semua Booking', 'Booking & Jamaah', 'Melihat semua booking dari semua cabang') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('bookings.view_branch', 'Lihat Booking Cabang', 'Booking & Jamaah', 'Melihat booking cabang pengguna') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('bookings.view_own', 'Lihat Booking Sendiri', 'Booking & Jamaah', 'Melihat booking milik pengguna sendiri') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('bookings.create', 'Buat Booking', 'Booking & Jamaah', 'Membuat booking baru') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('bookings.edit', 'Edit Booking', 'Booking & Jamaah', 'Mengubah detail booking') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('bookings.approve', 'Setujui Booking', 'Booking & Jamaah', 'Menyetujui booking') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('bookings.delete', 'Hapus Booking', 'Booking & Jamaah', 'Menghapus booking') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;

-- Payments
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('payments.view_all', 'Lihat Semua Pembayaran', 'Keuangan & Pembayaran', 'Melihat semua riwayat pembayaran') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('payments.view_branch', 'Lihat Pembayaran Cabang', 'Keuangan & Pembayaran', 'Melihat pembayaran cabang pengguna') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('payments.view_own', 'Lihat Pembayaran Sendiri', 'Keuangan & Pembayaran', 'Melihat pembayaran milik pengguna') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('payments.create', 'Buat Pembayaran', 'Keuangan & Pembayaran', 'Input bukti bayar baru') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('payments.verify', 'Verifikasi Pembayaran', 'Keuangan & Pembayaran', 'Validasi & konfirmasi pembayaran') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('payments.refund', 'Proses Refund', 'Keuangan & Pembayaran', 'Melakukan pengembalian dana') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('finance.reports', 'Laporan Keuangan', 'Keuangan & Pembayaran', 'Mengakses laporan laba rugi') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;

-- Customers
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('customers.view', 'Lihat Jamaah', 'Data Jamaah', 'Melihat profil jamaah') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('customers.create', 'Buat Jamaah', 'Data Jamaah', 'Membuat data jamaah baru') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('customers.edit', 'Edit Jamaah', 'Data Jamaah', 'Mengubah data jamaah') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('customers.edit_sensitive', 'Edit Data Sensitif', 'Data Jamaah', 'Mengubah data paspor/NIK') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('customers.delete', 'Hapus Jamaah', 'Data Jamaah', 'Menghapus data jamaah') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;

-- Operational
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('operational.manifest', 'Kelola Manifest', 'Operasional', 'Mengelola manifest keberangkatan') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('operational.visa', 'Update Status Visa', 'Operasional', 'Update status pengurusan visa') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('operational.view', 'Lihat Operasional', 'Operasional', 'Melihat data operasional') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('operational.manage', 'Kelola Operasional', 'Operasional', 'Mengelola data operasional') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;

-- Equipment
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('equipment.inventory', 'Kelola Stok', 'Perlengkapan', 'Kelola stok perlengkapan') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('equipment.distribute', 'Catat Serah Terima', 'Perlengkapan', 'Catat serah terima perlengkapan') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;

-- Leads
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('leads.view', 'Lihat Leads', 'Leads & Marketing', 'Melihat daftar leads') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('leads.create', 'Buat Leads', 'Leads & Marketing', 'Membuat leads baru') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('leads.edit', 'Edit Leads', 'Leads & Marketing', 'Mengubah detail leads') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('leads.delete', 'Hapus Leads', 'Leads & Marketing', 'Menghapus leads') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;

-- Packages
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('packages.view', 'Lihat Paket', 'Paket & Keberangkatan', 'Melihat daftar paket') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('packages.create', 'Buat Paket', 'Paket & Keberangkatan', 'Membuat paket baru') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('packages.edit', 'Edit Paket', 'Paket & Keberangkatan', 'Mengubah detail paket') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('packages.delete', 'Hapus Paket', 'Paket & Keberangkatan', 'Menghapus paket') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('departures.view', 'Lihat Keberangkatan', 'Paket & Keberangkatan', 'Melihat daftar keberangkatan') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('departures.create', 'Buat Keberangkatan', 'Paket & Keberangkatan', 'Membuat keberangkatan baru') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('departures.edit', 'Edit Keberangkatan', 'Paket & Keberangkatan', 'Mengubah detail keberangkatan') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('departures.delete', 'Hapus Keberangkatan', 'Paket & Keberangkatan', 'Menghapus keberangkatan') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;

-- System
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('users.view', 'Lihat Pengguna', 'Sistem & Pengaturan', 'Melihat daftar pengguna') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('users.create', 'Buat Pengguna', 'Sistem & Pengaturan', 'Membuat pengguna baru') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('users.edit', 'Edit Pengguna', 'Sistem & Pengaturan', 'Mengubah detail pengguna') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('users.delete', 'Hapus Pengguna', 'Sistem & Pengaturan', 'Menghapus pengguna') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('agents.view', 'Lihat Agen', 'Sistem & Pengaturan', 'Melihat daftar agen') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('agents.create', 'Buat Agen', 'Sistem & Pengaturan', 'Membuat agen baru') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('agents.edit', 'Edit Agen', 'Sistem & Pengaturan', 'Mengubah detail agen') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('agents.delete', 'Hapus Agen', 'Sistem & Pengaturan', 'Menghapus agen') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('master_data.view', 'Lihat Master Data', 'Sistem & Pengaturan', 'Melihat master data') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('master_data.manage', 'Kelola Master Data', 'Sistem & Pengaturan', 'Mengelola master data') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('settings.view', 'Lihat Pengaturan', 'Sistem & Pengaturan', 'Melihat pengaturan sistem') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('settings.manage', 'Kelola Pengaturan', 'Sistem & Pengaturan', 'Mengelola pengaturan sistem') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('dashboard.view', 'Lihat Dashboard', 'Sistem & Pengaturan', 'Akses dashboard utama') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('analytics.view', 'Lihat Analytics', 'Sistem & Pengaturan', 'Melihat analitik') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
INSERT INTO public.permissions_list (key, label, group_name, description) VALUES ('reports.view', 'Lihat Laporan', 'Sistem & Pengaturan', 'Melihat laporan') ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name, description = EXCLUDED.description;
